### ISSUE TITLE
README Env Variable Not Consistent with Script

### ISSUE THREAD

**Issue by shonigmann** [jasmeet0915/workon_ros#1]
The README specifies to export:
`export ROS_WORKON_HOME=$HOME/ros_workspaces`

But the script expects:
`WORKON_ROS_HOME`

Anyways, thanks for the tool! Seems to work well once my `.bashrc` is setup properly.

**Comment by jasmeet0915** [comment]
Hi @shonigmann, Thanks for pointing this out!
This has been fixed in the latest commit 4383f473c22e154f12fde74817f96960247d92de.
